steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/yfinance_stock', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'yfinance_stock', '--image', 'gcr.io/$PROJECT_ID/yfinance_stock', '--region', 'asia-east1', '--platform', 'managed', '--allow-unauthenticated']
images: 
- 'gcr.io/$PROJECT_ID/yfinance_stock'
